from typing import Tuple

# Crawl from https://osu.ppy.sh/wiki/en/osu%21_Program_Files/User_Configuration_File using:
# // select column and sort by its vertical offset
# es = $('table tr td:nth-child(1) > code').sort(function(a, b) {
#     return $(a).offset().top < $(b).offset().top;
# })
# options = []
# for (let i = 0; i < 160; i++) {
#     options.push(es[i].innerHTML)
# }

config_key: Tuple[str, ...] = (
    'Username',
    'Password',
    'SaveUsername',
    'SavePassword',
    'Language',
    'ShowUnicode',
    'AlternativeChatFont',
    'FrameSync',
    'FpsCounter',
    'CompatibilityContext',
    'ForceFrameFlush',
    'DetectPerformanceIssues',
    'Width',
    'Height',
    'WidthFullscreen',
    'HeightFullscreen',
    'Fullscreen',
    'Letterboxing',
    'LetterboxPositionX',
    'LetterboxPositionY',
    'SnakingSliders',
    'Video',
    'ShowStoryboard',
    'ComboBurst',
    'HitLighting',
    'Shaders',
    'BloomSoftening',
    'ScreenshotFormat',
    'MenuSnow',
    'MenuParallax',
    'ShowMenuTips',
    'MenuVoice',
    'MenuMusic',
    'SeasonalBackgrounds',
    'SongSelectThumbnails',
    'DimLevel',
    'IHateHavingFun',
    'ProgressBarType',
    'ScoreMeter',
    'ScoreMeterScale',
    'KeyOverlay',
    'HiddenShowFirstApproach',
    'ManiaSpeedBPMScale',
    'UsePerBeatmapManiaSpeed',
    'DisplayStarsMinimum',
    'DisplayStarsMaximum',
    'AudioDevice',
    'VolumeUniversal',
    'VolumeMusic',
    'VolumeEffect',
    'IgnoreBeatmapSamples',
    'Offset',
    'Skin',
    'IgnoreBeatmapSkins',
    'SkinSamples',
    'UseTaikoSkin',
    'UseSkinCursor',
    'CursorSize',
    'AutomaticCursorSizing',
    'ComboColourSliderBall',
    'MouseSpeed',
    'RawInput',
    'AbsoluteToOsuWindow',
    'ConfineMouse',
    'MouseDisableWheel',
    'MouseDisableButtons',
    'CursorRipple',
    'Tablet',
    'Wiimote',
    'VideoEditor',
    'EditorDefaultSkin',
    'EditorSnakingSliders',
    'EditorHitAnimations',
    'EditorFollowPoints',
    'EditorStacking',
    'Ticker',
    'AutoChatHide',
    'ChatHighlightName',
    'ChatMessageNotification',
    'ChatAudibleHighlight',
    'DisplayCityLocation',
    'ShowSpectators',
    'AutoSendNowPlaying',
    'PopupDuringGameplay',
    'NotifyFriends',
    'AllowPublicInvites',
    'DiscordRichPresence',
    'YahooIntegration',
    'MsnIntegration',
    'AutomaticDownload',
    'AutomaticDownloadNoVideo',
    'ChatFilter',
    'ChatRemoveForeign',
    'LogPrivateMessages',
    'BlockNonFriendPM',
    'IgnoreList',
    'HighlightWords',
    'keyOsuLeft',
    'keyOsuRight',
    'keyOsuSmoke',
    'keyTaikoInnerLeft',
    'keyTaikoInnerRight',
    'keyTaikoOuterLeft',
    'keyTaikoOuterRight',
    'keyFruitsLeft',
    'keyFruitsRight',
    'keyFruitsDash',
    'keyIncreaseSpeed',
    'keyDecreaseSpeed',
    'keyPause',
    'keySkip',
    'keyToggleScoreboard',
    'keyIncreaseAudioOffset',
    'keyDecreaseAudioOffset',
    'keyQuickRetry',
    'keyToggleFrameLimiter',
    'keyToggleChat',
    'keyToggleExtendedChat',
    'keyScreenshot',
    'keyVolumeIncrease',
    'keyVolumeDecrease',
    'keyDisableMouseButtons',
    'keyBossKey',
    'keySelectTool',
    'keyNormalTool',
    'keySliderTool',
    'keySpinnerTool',
    'keyNewComboToggle',
    'keyWhistleToggle',
    'keyFinishToggle',
    'keyClapToggle',
    'keyGridSnapToggle',
    'keyDistSnapToggle',
    'keyNoteLockToggle',
    'keyNudgeLeft',
    'keyNudgeRight',
    'keyHelpToggle',
    'keyJumpToBegin',
    'keyPlayFromBegin',
    'keyAudioPause',
    'keyJumpToEnd',
    'keyGridChange',
    'keyTimingSection',
    'keyInheritingSection',
    'keyRemoveSection',
    'keyEasy',
    'keyNoFail',
    'keyHalfTime',
    'keyHardRock',
    'keySuddenDeath',
    'keyDoubleTime',
    'keyHidden',
    'keyFlashlight',
    'keyRelax',
    'keyAutopilot',
    'keySpunOut',
    'keyAuto',
    'keyScoreV2',

    # mania layouts, K means 1-18
    # 'ManiaLayouts#K',
    # 'ManiaLayouts#KSplit',
    *[f'ManiaLayouts#{i}' for i in range(1, 19)],
    *[f'ManiaLayouts#{i}Split' for i in range(1, 19)]
)
